/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import ru.rudn.science.belov_course.task1.task1
import ru.rudn.science.belov_course.task2.task2
import ru.rudn.science.belov_course.task3.task3
import ru.rudn.science.belov_course.task4.task4

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

tasks {
    val build by registering {
        doLast {
            task1()
            task2()
            task3()
            task4()
        }
    }

    wrapper {
        gradleVersion = "6.1"
        distributionType = Wrapper.DistributionType.ALL
    }
}

